# Generated by Django 5.2 on 2025-04-20 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ism', models.CharField(max_length=255)),
                ('mini_tavsif', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('kalit_slova', models.JSONField(default=list)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eslatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ism', models.CharField(max_length=255)),
                ('tarkibi', models.TextField()),
                ('rasm', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ism', models.CharField(max_length=255)),
                ('rasm', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ism', models.CharField(max_length=255)),
                ('rasm', models.URLField()),
                ('havola_na_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bannerlar', to='Parfumeriya.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ism', models.CharField(max_length=255)),
                ('mini_tavsif', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kalit_slova', models.JSONField(default=list)),
                ('ball', models.FloatField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('eslatmalar', models.ManyToManyField(blank=True, related_name='mahsulotlar', to='Parfumeriya.eslatma')),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='Parfumeriya.kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Sharh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ball', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sharh', models.TextField()),
                ('moderatsiya_qilingan', models.BooleanField(default=False)),
                ('moderator', models.CharField(blank=True, max_length=255, null=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharhlar', to='Parfumeriya.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hajm', models.CharField(max_length=50)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantlar', to='Parfumeriya.mahsulot')),
            ],
        ),
    ]
